In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('home_fav.csv')

In [3]:
df.head()

,game_id,date,Visitor Team,Visitor Pitcher,Home Team,Home Pitcher,Open Visitor ML,Close Visitor ML,Home Open ML,Home Close ML,...,Visitor RL,Visitor RL Price,Home RL,Home RL Price,final_spread,payout_ratio,winnings,wager,no_cover,random
0,4,2014-03-31,CUB,SAMARDZIJA-R,PIT,FLIRIANO-L,145,170,-165,-190,...,1.5,-145,-1.5,125,1,1.689655,16.896552,10,1.0,0
1,8,2014-03-31,COL,DELAROSA-L,MIA,JFERNANDZ-R,140,130,-155,-145,...,1.5,-175,-1.5,155,9,-1.000000,-10.000000,10,0.0,1
2,10,2014-03-31,KAN,JSHIELDS-R,DET,JVERLANDE-R,140,133,-160,-148,...,1.5,-170,-1.5,150,1,1.588235,15.882353,10,1.0,0
3,12,2014-03-31,TOR,RDICKEY-R,TAM,DPRICE-L,145,144,-165,-164,...,1.5,-155,-1.5,135,7,-1.000000,-10.000000,10,0.0,0
4,13,2014-03-31,MIN,RNOLASCO-R,CWS,CSALE-L,145,155,-165,-175,...,1.5,-145,-1.5,125,2,-1.000000,-10.000000,10,0.0,0

In [10]:
df['Home Pitch Hand'] = df['Home Pitcher'].str.split('-', expand=True)[1]

In [12]:
df['Visitor Pitch Hand'] = df['Visitor Pitcher'].str.split('-', expand=True)[1]

In [13]:
df.head()

,game_id,date,Visitor Team,Visitor Pitcher,Home Team,Home Pitcher,Open Visitor ML,Close Visitor ML,Home Open ML,Home Close ML,...,Home RL,Home RL Price,final_spread,payout_ratio,winnings,wager,no_cover,random,Home Pitch Hand,Visitor Pitch Hand
0,4,2014-03-31,CUB,SAMARDZIJA-R,PIT,FLIRIANO-L,145,170,-165,-190,...,-1.5,125,1,1.689655,16.896552,10,1.0,0,L,R
1,8,2014-03-31,COL,DELAROSA-L,MIA,JFERNANDZ-R,140,130,-155,-145,...,-1.5,155,9,-1.000000,-10.000000,10,0.0,1,R,L
2,10,2014-03-31,KAN,JSHIELDS-R,DET,JVERLANDE-R,140,133,-160,-148,...,-1.5,150,1,1.588235,15.882353,10,1.0,0,R,R
3,12,2014-03-31,TOR,RDICKEY-R,TAM,DPRICE-L,145,144,-165,-164,...,-1.5,135,7,-1.000000,-10.000000,10,0.0,0,L,R
4,13,2014-03-31,MIN,RNOLASCO-R,CWS,CSALE-L,145,155,-165,-175,...,-1.5,125,2,-1.000000,-10.000000,10,0.0,0,L,R

In [14]:
df['winnings'].sum()

36285.064690993735

In [15]:
df['wager'].sum()

65510

In [26]:
df['Home Pitcher'] = df['Home Pitcher'].str[:-2]

In [28]:
df['Visitor Pitcher'] = df['Visitor Pitcher'].str[:-2]